server:
  port: 9000
spring:
  application:
    name: ad-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
  # 网关前缀
  prefix: /imooc
  routes:
    sponsor:
      path: /ad-sponsor/**
      # 微服务名字
      serviceId: eureka-client-ad-sponsor
      # 是否去除前缀, 在此不要去除
      strip-prefix: false
    search:
      path: /ad-search/**
      serviceId: eureka-client-ad-search
      strip-prefix: false
